CREATE TABLE IF NOT EXISTS teste(
id INT PRIMARY KEY AUTO_INCREMENT
);

SHOW TABLES;

DROP TABLE teste;

CREATE TABLE IF NOT EXISTS administradores(
id_administrador INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(200) UNIQUE NOT NULL,
cpf VARCHAR(14) UNIQUE NOT NULL,
email VARCHAR(500) UNIQUE NOT NULL,
senha VARCHAR(1000) NOT NULL 
);

CREATE TABLE IF NOT EXISTS clientes(
id_cliente INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(200) UNIQUE NOT NULL,
cnpj VARCHAR(18) UNIQUE NOT NULL,
email VARCHAR(500) UNIQUE NOT NULL,
senha VARCHAR(1000) NOT NULL 
);

CREATE TABLE IF NOT EXISTS profissionais(
id_profissional INT PRIMARY KEY AUTO_INCREMENT,
re VARCHAR(100) NOT NULL UNIQUE,
nome VARCHAR(200) NOT NULL,
cpf VARCHAR(14) NOT NULL,
cnpj VARCHAR(18),
salario numeric(14,2)
);

CREATE TABLE IF NOT EXISTS produtos(
id_produto INT PRIMARY KEY AUTO_INCREMENT,
CHECK 

);






